### ISSUE TITLE
image adamradocz/boinc-manager-web:arm32v7 could not be accessed on a registry to record

### ISSUE THREAD

**Issue by AndreasPrang** [adamradocz/boinc-manager#3]
I tried to run your setup on my Raspberry Pi Docker Cluster with 5 nodes

I think the arm32v7 image is missing on docker hub?

**Comment by adamradocz** [comment]
You have to build the `arm` version for yourself.
Clone the repository and run the following command inside the cloned directory: `docker build -t boinc-manager-web .`
